Repository yuu-eguci/yahoo-login-web2, pull requests merged in 2019-12, with the labels that each got.

#6 feature/#1_github
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#7 feature/#2_init
  .gitignore
  app.js
  bin/www
  package-lock.json
  package.json
  public/stylesheets/style.css
  routes/index.js
  routes/users.js
  views/error.ejs
  views/index.ejs
Labels: enhancement

#8 feature/#2_init
  .gcloudignore
  .gitignore
  app.js
  app.yaml
  package-lock.json
  package.json
  public/images/favicon.png
  routes/index.js
  routes/inspection.js
  routes/mypage.js
  routes/users.js
  views/index.ejs
  views/mypage.ejs
Labels: enhancement

#12 feature/#2_init
  routes/inspection.js
  routes/mypage.js
  views/error.ejs
Labels: bug

#17 feature/#9_refactoring
  app.js
  routes/index.js
  routes/inspection.js
  routes/mypage.js
Labels: refactoring

#18 Feature/#11 refactoring request
  app.js
  package-lock.json
  package.json
  routes/inspection.js
  routes/test.js
  views/test.ejs
Labels: refactoring

#19 #3 Use random string for state
  routes/index.js
Labels: enhancement

#21 Feature/#20 doc
  README.md
  app.js
  routes/index.js
  routes/inspection.js
Labels: documentation

#22 Feature/#5 id token
  routes/inspection.js
Labels: enhancement

#23 Feature/#5 id token
  routes/inspection.js
Labels: enhancement

#27 feature/#26_design
  views/index.ejs
  views/logout.ejs
  views/mypage.ejs
Labels: enhancement
